Makefile, docs/install.md, docs/snapshot.md, manifest/manifest.yaml, scripts/generate_manifest.sh, scripts/upload_docker_images.sh
1. generate_manifest.sh builds manifest for a given branch;
1. upload_docker_images.sh builds and uploads docker images for a given branch.
Those scripts are meant to be invoked only by Makefile targets.
=> Add scripts

docs/configuration.md, docs/install.md, mkdocs.yml, scripts/upload_docker_images.sh
- mention how to install sveltosctl (not installed by default)
- mention error, which can be ignored, if prometheus operator is not installed.
=> Various minor addition

docs/blogs.md, docs/index.md, docs/snapshot.md
=> Add github star button

Makefile, docs/addons.md, docs/blogs.md, docs/configuration.md, docs/index.md, docs/install.md, docs/labels_management.md, docs/multi-tenancy.md, docs/register-cluster.md, docs/snapshot.md, docs/template.md, docs/visibility.md, manifest/manifest.yaml
=> Prepare for release v0.4.0

Makefile, docs/addons.md, docs/blogs.md, docs/configuration.md, docs/configuration_drift.md, docs/index.md, docs/install.md, docs/labels_management.md, docs/multi-tenancy.md, docs/visibility.md, manifest/manifest.yaml, mkdocs.yml
=> Add multi-tenancy section for main

docs/configuration.md, docs/notifications.md
Add another HealthCheck example finding all degraded Certificates
=> Add Classifier example with Lua script

docs/visibility.md
In the visibility section, add a reference to show resources command.
=> Add reference to show resources

docs/quick_start.md, manifest/manifest.yaml
Update manifest post release v0.15.1
=> Add quickstart instruction

manifest/manifest.yaml
No label is needed on projectsveltos namespace
=> Fix manifest

manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml, scripts/generate_manifest.sh, scripts/upload_docker_images.sh
Updated scripts to consider shard-controller both when generating manifest and when building/uploading docker images.
=> Add shard-controller

manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml, scripts/generate_manifest.sh
Shard controller has new option
=> Fix v0.19.0 manifest

Makefile, manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml, manifest/sveltosctl_manifest.yaml
=> Prepare dev to main merge

docs/blogs.md, docs/register/claudie.md, docs/register/clusterapi.md, mkdocs.yml
Describe how Sveltos can automatically manage Claudie powered clusetrs.
=> Add Claudie section

manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml
Sveltoscluster YAML was missing due to an issue with sveltoscluster repo which has now been fixed
=> Fix manifest with sveltoscluster YAML

manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml
Removes duplicate `projectsveltos` namespace objects in `manifest/agents_in_mgmt_cluster_manifest.yaml`. 
Fixes: #203
=> fix error with deploying with kustomization

docs/install/install.md, docs/sveltosctl/snapshot.md, docs/sveltosctl/sveltosctl.md, docs/sveltosctl/techsupport.md, docs/sveltosctl/visibility.md, mkdocs.yml
Group together the sveltosctl section. Update the individual sections to provide a clearer message to the end user.
Changes performed:
- Move the sveltosctl.md section under sveltosctl
- Update individual sveltosctl sections
- Update the mkdocs.yml file and move the section sveltosctl under the install section
=> Update the Sveltosctl Section

manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml
=> Update main manifest

docs/addons/raw_yaml.md
With release v0.23.0 Sveltos can seamlessly integrate with Flux to automatically deploy YAML manifests stored in a Git repository.
=> Add section to explain Sveltos, Flux integration

docs/addons/raw_yaml.md, docs/deployment_order/depends_on.md, docs/deployment_order/depends_on_with_health_checks.md, docs/deployment_order/manifest_order.md, docs/deployment_order/order_with_events.md, mkdocs.yml
- Update the Deployment Order section
=> Update the Deployment Order section

docs/addons/addons.md, docs/addons/example_flux_sources.md, docs/addons/helm_charts.md, docs/addons/kustomize.md, docs/addons/raw_yaml.md, docs/addons/rolling_update_strategy.md, mkdocs.yml
- Restructure the add-ons section
- Add a new example with Flux sources
=> Restructure the add-ons section

docs/use_cases/use_case_2.md, docs/use_cases/use_case_multitenancy.md, docs/use_cases/use_case_platform_admin_multicloud.md, mkdocs.yml
- Define the multitenancy use case
- Perform small typos on the 1st use case
=> Define the multitenancy use case

mkdocs.yml
Fix the broken reference link to the mkdocs
=> Fix the broken reference link to the mkdocs

mkdocs.yml
Move it between the "Templating" section and and the "Features" section.
=> Move 'resource order' section

docs/blogs.md
- Update the Blogs page with more recent resources
=> Update the Blogs page

docs/addons/example_flux_sources.md
Added one example to deploy Nginx helm chart.
Added one example to deploy Kyverno ClusterPolicies.
=> Update Flux, Sveltos integration

docs/addons/example_flux_sources.md, docs/use_cases/use_case_flux_integration.md
- Update the Flux documentation with an updated example
- Add relevant notes about the Flux installation and the templating capabilities alongside Sveltos requirements
- Small wording updates
=> Update the Flux documentation with an updated example

docs/blogs.md
- Include the Sveltos and Flux easy to follow deployment to the articles section
=> Update the articles section

docs/getting_started/install/install.md
Update the Helm instructions for the Sveltos installation on a management cluster
=> Update the Helm instructions

docs/getting_started/install/install.md
Remove the duplicate helm install command with the helm list command
=> Remove the duplicate helm install command with the helm list command

docs/addons/raw_yaml.md
Old example was failing with following error:
```
failureMessage: no matches for kind "GatewayClass" in version "gateway.networking.k8s.io/v1beta1"
```
Replaced it with one that successfully deploys a namespace and a deployment.
=> Change the YAML example

docs/getting_started/install/install.md
=> Enhance two modes Sveltos can be installed

docs/getting_started/install/install.md
Update the Install section to provide more clarity on the different installation modes available
=> Update the Install section

docs/deployment_order/depends_on_with_health_checks.md, docs/deployment_order/manifest_order.md, docs/deployment_order/order_with_events.md, docs/features/configuration_drift.md, docs/features/multi-tenancy-full-isolation.md, docs/features/multi-tenancy-sharing-cluster.md, docs/getting_started/install/install.md, docs/getting_started/sveltosctl/visibility.md, docs/help_and_tutorials/troubleshooting.md, docs/observability/display_resources.md, docs/register/register_claudie_cluster.md, docs/scalability/sharding.md, docs/use_cases/use_case_flux_integration.md, docs/use_cases/use_case_multitenancy.md, docs/use_cases/use_case_platform_admin_multicloud.md, mkdocs.yml
- Create a new section with the name Help and Tutorials
- Create an initial troubleshooting guide
=> Create a new section with the name Help and Tutorials

docs/addons/helm_charts.md, docs/addons/kustomize.md, docs/template/template.md, kustomize/base/register-mgmt-cluster.yaml, kustomize/components/crds/clusterconfigurations.config.projectsveltos.io.yaml, kustomize/components/crds/clusterprofiles.config.projectsveltos.io.yaml, kustomize/components/crds/clusterreports.config.projectsveltos.io.yaml, kustomize/components/crds/clustersummaries.config.projectsveltos.io.yaml, kustomize/components/crds/eventtriggers.lib.projectsveltos.io.yaml, kustomize/components/crds/lib.projectsveltos.io_accessrequests.yaml, kustomize/components/crds/lib.projectsveltos.io_classifierreports.yaml, kustomize/components/crds/lib.projectsveltos.io_classifiers.yaml, kustomize/components/crds/lib.projectsveltos.io_clusterhealthchecks.yaml, kustomize/components/crds/lib.projectsveltos.io_clustersets.yaml, kustomize/components/crds/lib.projectsveltos.io_debuggingconfigurations.yaml, kustomize/components/crds/lib.projectsveltos.io_eventreports.yaml, kustomize/components/crds/lib.projectsveltos.io_eventsources.yaml, kustomize/components/crds/lib.projectsveltos.io_healthcheckreports.yaml, kustomize/components/crds/lib.projectsveltos.io_healthchecks.yaml, kustomize/components/crds/lib.projectsveltos.io_reloaderreports.yaml, kustomize/components/crds/lib.projectsveltos.io_reloaders.yaml, kustomize/components/crds/lib.projectsveltos.io_resourcesummaries.yaml, kustomize/components/crds/lib.projectsveltos.io_rolerequests.yaml, kustomize/components/crds/lib.projectsveltos.io_sets.yaml, kustomize/components/crds/lib.projectsveltos.io_sveltosclusters.yaml, kustomize/components/crds/profiles.config.projectsveltos.io.yaml, manifest/agents_in_mgmt_cluster_manifest.yaml, manifest/manifest.yaml, manifest/sveltosctl_manifest.yaml
This PR contains various updates:
1. An example with OCI chart
2. Section explaining Kustomize Values/ValuesFrom
Fixes #270
Fixes #272
=> Update documentation post release v0.29.0

docs/help_and_tutorials/troubleshooting.md
Small updates to the tshoot section. Nothing major.
=> Update the tshoot section

docs/getting_started/install/install.md, docs/index.md
- Clearly describe what Sveltos is
- Clearly describe Sveltos features
- Outline why Sveltos over other CI/CD tools
=> Update the index.md page

mkdocs.yml
Update the mkdocs material features and theme. Now, we support
- Code annotation
- Admonition
- Code highlight
=> Update the mkdocs material features and theme

docs/addons/addons.md, docs/addons/helm_charts.md, docs/addons/raw_yaml.md, docs/addons/rolling_update_strategy.md, docs/deployment_order/depends_on.md, docs/events/addon_event_deployment.md, docs/events/example_service_event_trigger.md, docs/getting_started/install/install.md, docs/getting_started/sveltosctl/sveltosctl.md, docs/help_and_tutorials/troubleshooting.md, docs/observability/example_addon_notification.md, docs/observability/notifications.md, docs/register/register-cluster.md, docs/template/example_multicluster_iteration_template.md, docs/template/template_generic_examples.md, docs/use_cases/use_case_flux_integration.md, docs/use_cases/use_case_multitenancy.md, mkdocs.yml
Update the note,tips and warning areas with the new feature
=> Update the note,tips and warning areas with the new feature

docs/getting_started/install/quick_start.md, docs/getting_started/sveltosctl/snapshot.md, docs/getting_started/sveltosctl/techsupport.md, docs/getting_started/sveltosctl/visibility.md, docs/index.md, docs/register/register-cluster.md, docs/register/register_management_cluster.md, docs/template/intro_template.md, docs/use_cases/use_case_flux_integration.md, docs/use_cases/use_case_multitenancy.md, docs/use_cases/use_case_platform_admin_multicloud.md
- Small changes to the index.md file
- Update the code sample as examples with annotations (Sections Use Cases, Getting Started, Register Clusters have been updated)
=> Reformat Docu

docs/addons/addons.md, docs/index.md
=> Fix small typos

docs/getting_started/install/install.md
Update the install section to include more information about cert-mamager as a prerequisite
=> Update the install section to be more informative

docs/blogs.md
- Update the blog posts area with the latest information
=> Update the blog posts area with the latest info

docs/addons/raw_yaml.md, docs/features/configuration_drift.md, docs/register/cluster_maintenance_window.md, mkdocs.yml
Closes #338 
Closes #333 
Closes #332
=> Update documentatio with new features

docs/getting_started/install/dashboard.md
- Minor updates Sveltos Dashboard docu
=> Small updates Sveltos Dashboard docu

docs/register/register-cluster.md
Add a section explaining which resources need to be created to programmatically register a cluster with Sveltos (so without using sveltosctl)
=> Programmatically registers a cluster

docs/getting_started/install/dashboard.md
This is latest video covering:
- how different admin can login via bearer token
- how to visualize what add-ons and applications are deployed on each cluster
=> Update Dashboard video

docs/events/bd-as-a-service.md
=> Temporary add link

docs/assets/fetch-postgres-data.yaml
Those are referenced by Sveltos resources.
=> Add namespace to ConfigMaps

docs/getting_started/install/dashboard.md
Fixes [792](https://github.com/projectsveltos/addon-controller/issues/792)
=> Sveltos Dashboard: add note on min Kubernetes version

docs/getting_started/install/dashboard.md, docs/getting_started/install/install.md, docs/getting_started/install/quick_start.md
- Minor updates to the installation sections
- Update the warning about version compatibility of deployments
=> Minor updates to the installation sections

docs/assets/propgate-secret.yaml, docs/events/secret_distribution.md, docs/template/intro_template.md, mkdocs.yml
The example shows how to replicate a Secret to managed cluster when namespaces with certain labels are created.
=> Add concrete example using ConfigMapGenerator

docs/register/register-cluster.md
=> add cluster registration sample for Kamaji

docs/addons/clusterprofile.md, docs/addons/profile.md
=> ClusterSelector: add an example using matchExpressions

docs/features/dryrun.md, docs/getting_started/install/telemetry.md, docs/getting_started/sveltosctl/snapshot.md, docs/template/examples.md, docs/template/intro_template.md, docs/template/template_generic_examples.md, mkdocs.yml
Small updates on sections getting_started, template and features
=> Small updates on sections getting_started, template and features

docs/getting_started/install/grafanadashboard.md, docs/getting_started/install/install.md
- Update broken links for Sveltos Dashboard and Grafana Dashboard
=> Link corrections

docs/addons/example_flux_sources.md
- Update the Flux docu to include a more advanced template example
=> Update the Flux example docu

docs/features/configuration_drift.md
Sligthly rewrite whats needed to pull sveltos-agent from private registry
=> Private registry

docs/getting_started/install/grafanadashboard.md
Update the Grafana dashboard documentation with relevant information about the dashboard setup
=> Update the Grafana dashboard docu

docs/template/template_generic_examples.md
Adds extra Sveltos template example for creating a bit more complex Kubernetes objects in managed clusters.
=> Add `cloud-config` use-case for Sveltos template examples

docs/register/token-renewal.md
Add a supplementary section under token renewal documentation to explain the necessary privileges and processes involved in token rotation for a Sveltos-managed cluster.
=> Add detailed notes on token renewal in docs

docs/getting_started/install/air_gapped_installation.md, mkdocs.yml
Include an air-gapped section below the installation section
=> Include an air-gapped section below the installation section

docs/features/configuration_drift.md, docs/getting_started/install/air_gapped_installation.md
- Few corrections Air-gapped installation
- Update the Drift Detection docu
=> Minor Updates Air-gapped installation and Drift Detection

docs/addons/clusterprofile.md, docs/addons/helm_charts.md, docs/addons/profile.md
=> Add ContinueOnError and ContinueOnConflict description

docs/addons/helm_charts.md
=> Private registry: basic auth

docs/getting_started/install/install.md
- Include a note for  **v1alpha1** version CRDs
=> Update v1alpha1 CRDs section

docs/template/intro_template.md, docs/template/lua.md, mkdocs.yml
=> Use Lua to generate at run time the resources to be deployed

docs/events/nats.md, docs/getting_started/install/air_gapped_installation.md, mkdocs.yml
=> Add NATS documentation

docs/getting_started/install/dashboard.md
- Fix the reference outline Sveltos Dashboard docu
=> Fix the reference outline

docs/events/example_loadbalancer.md, docs/getting_started/install/install.md
Fixes [1043](https://github.com/projectsveltos/addon-controller/issues/1043)
=> Add not about Sveltos Helm chart for CRDs

docs/register/readiness_liveness_checks.md
- Small updates about the readiness and liveness cluster health checks
=> Small updates about the readiness and liveness health checks

docs/getting_started/install/air_gapped_installation.md
- Small fixes to Air-gapped installation docu
=> Update the air-gapped documentation

mkdocs.yml
- Update the copyright date on the mkdocs.yml file
=> Update the copyright date on the mkdocs.yml file

docs/addons/example_flux_sources.md, docs/events/db-as-a-service-multiple-db-per-cluster.md
We used to get warnings like this one
=> Fix footnote with no anchor errors

mkdocs.yml
- Minor: reorganise the mkdocs sections
=> Reorganise the mkdocs sections

docs/getting_started/install/install.md
- Installation: Include a drop down note for longer note text
=> Include a drop down note for longer note text

docs/getting_started/install/quick_start.md
- Rewrite the quick-start guide
=> Rewrite the quick-start guide

docs/getting_started/optional/dashboard.md
- Update the Sveltos dashboard installation options
=> Update the Sveltos dashboard installation options

docs/register/register-cluster.md, docs/template/additional_template_info.md, docs/template/intro_template.md, mkdocs.yml
- Update the introduction to Sveltos templates section into two .md files
=> Update Sveltos Templating Section

docs/addons/helm_charts.md, docs/addons/raw_yaml.md, mkdocs.yml
Small updates on the add-ons section
=> Small updates on the add-ons section

docs/register/register-cluster.md
- Fix Sveltos cluster registration indentation
=> Fix indentation for the programmatic cluster registration

docs/addons/helm_charts.md, docs/events/addon_event_deployment.md, docs/events/generators.md
Fixes [1189](https://github.com/projectsveltos/addon-controller/issues/1189)
=> Update events template section

docs/events/example_secrets_on_demand.md, docs/events/generators.md, docs/events/templating.md, mkdocs.yml
- Split the events templating docu into three separate pages
- Update the mkdocs to include new pages
=> Refactor the events templating page

docs/features/labels_management.md
- Include the metrics-based classifier example
=> Include the metrics-based classifier example

docs/register/register-cluster.md
- Update the registration section based on Issue #557
=> Update the registration section based on Issue #557

docs/events/addon_event_deployment.md, docs/events/nats.md
- Update the Events Framework docu to include the CEL integration
=> Update the Events Framework docu to include the CEL integration

docs/events/addon_event_deployment.md, docs/features/labels_management.md, docs/features/techsupport.md, docs/observability/notifications.md, docs/register/readiness_liveness_checks.md
Update the below documentation to include the CEL support note.
- Classifier
- EventSource
- HealthCheck
- SveltosCluster liveness and readiness checks
- Techsupport
=> Update the related docu to include the CEL support note

.github/workflows/main.yml, .github/workflows/prod.yml, mkdocs.yml, overrides/main.html
Update the documentation to include Mike plugin for versioning
=> Update the documentation to include Mike plugin for versioning

docs/events/nats.md
This updates docs to match the new configuration set in https://github.com/projectsveltos/sveltos-agent/pull/406.
fixes https://github.com/projectsveltos/sveltos-agent/issues/405
=> updates docs to match revised JetStream config

docs/addons/example_flux_sources.md, docs/addons/kustomize.md
- Update the kustomize section
- Update the section to be clearer
=> Update the kustomize section

docs/events/addon_event_deployment.md, docs/getting_started/install/install.md, docs/register/register-cluster.md
Update the documentation to satisfy Issue #604
=> Update the documentation to satisfy Issue #604

docs/register/register-cluster.md
-Update the Helm chart link to point to the registerMgmtCluster argument
=> Update the Helm chart link to point to the registerMgmtCluster argument

docs/register/register_cluster_pull_mode.md
- Update instructions for Sveltos Pull Mode
=> Include correct instructions about the Pull Mode registration

docs/events/addon_event_deployment.md, docs/getting_started/optional/dashboard.md
- Fix href link
- Update the dashboard command line arguments for Authentication. Include them in a table instead
- Small changes to the dashboard docu
=> Minor Fixes

docs/javascript/extra.js, mkdocs.yml
- We included a .js script to enhance the copy functionality of mkdocs. More details in the comments section of the respective file.
=> Potential Fix #618

docs/template/template_overlays_examples.md, mkdocs.yml
=> Add an example with overlays

docs/blogs.md
- Update Blog Posts section
- Update the start outline to fit the Sveltos landing page
=> Update the blogs section

docs/addons/kustomize.md, docs/events/templating.md, docs/getting_started/install/air_gapped_installation.md
Add documentation for sveltos-applier upgrade with custom patches.
=> Event framework: add an example to patch a resource

docs/features/mcp.md, docs/register/features/pausing.md
=> Updates for PR #638

docs/archive.md, mkdocs.yml, overrides/main.html
- Potential docu archive section
=> Include the documentation archive page
